package domain.modelo.entities.Entidades.Usuario;

public enum Permiso {
    // SOLICITUD
    CREAR_SOLICITUD, VER_SOLICITUD, EDITAR_SOLICITUD, ELIMIAR_SOLICITUD,
    // CONTACTO
    CREAR_CONTACTO, VER_CONTACTO, EDITAR_CONTACTO, ELIMIAR_CONTACTO,
    // TRANSPORTE
    CREAR_TRANSPORTE, VER_TRANSPORTE, EDITAR_TRANSPORTE, ELIMIAR_TRANSPORTE,
    // FE
    CREAR_FE, VER_FE, EDITAR_FE, ELIMIAR_FE,
    // ORGANIZACION
    CREAR_ORGANIZACION, VER_ORGANIZACION, EDITAR_ORGANIZACION, ELIMIAR_ORGANIZACION,
    // MIEMBRO
    CREAR_MIEMBRO, VER_MIEMBRO, EDITAR_MIEMBRO, ELIMIAR_MIEMBRO,
    // MEDICIONES
    CARGA_MEDICIONES,
    // TRAYECTO
    CREAR_TRAYECTO, VER_TRAYECTO, EDITAR_TRAYECTO, ELIMIAR_TRAYECTO,
    // SECTOR
    CREAR_SECTOR, VER_SECTOR, EDITAR_SECTOR, ELIMIAR_SECTOR,
    //SECTOR_TERRITORIAL
    VER_SECTOR_TERRITORIAL, EDITAR_SECTOR_TERRITORIAL, ELIMINAR_SECTOR_TERRITORIAL, CREAR_SECTOR_TERRITORIAL,
    //AGENTE_SECTORIAL
    VER_AGENTE_SECTORIAL, EDITAR_AGENTE_SECTORIAL, ELIMINAR_AGENTE_SECTORIAL, CREAR_AGENTE_SECTORIAL,
    //REPORTES
    VER_REPORTES
}
